name: Publish to npm

on:
  push:
    tags:
    - "v*"

jobs:
  quality-check:
    uses: ./.github/workflows/qualityCheck.yml
    secrets: inherit

  publish:
    needs: quality-check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NODE_ENV: production
      CI: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "latest"

    - name: Install dependencies
      run: bun install

    - name: Build package
      run: bun run build

    - name: Validate version tag
      run: |
        if [[ ! ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version tag format"
          exit 1
        fi

    - name: Publish to npm
      run: bun publish --access public
      env:
        NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
