name: Quality Check

on:
  push:
    branches:
    - "**"
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      quality_passed: ${{ steps.quality_check.outputs.passed }}
    env:
      NODE_ENV: production
      CI: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "latest"

    - name: Install dependencies
      run: bun install

    - name: Run typecheck
      run: bun run typecheck

    - name: Run lint
      run: bun run lint:CI

    - name: Run test
      run: bun test

    - name: Run build
      run: bun run build

    - run: bunx pkg-pr-new publish --bin --binaryApplication

    - name: Set quality check output
      id: quality_check
      run: echo "passed=true" >> $GITHUB_OUTPUT
